### ISSUE TITLE
Add block data to commits

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-block-committer#56]
Right now the block committer only commits the block hash, but we should add for this commits also the block data, but considering the size of the block data to split in multiple commits if needed

**Comment by digorithm** [comment]
Closing as https://github.com/FuelLabs/fuel-block-committer/pull/85 mostly solved it. Still, we only post the tx hashes from a block, but now it can do it through blobs and not only calldata. We still need to figure out what data we want to post (a decision coming mostly from the core) and how DA compression will work here.
