### ISSUE TITLE
Define a mechanism for allowing fuel-core to query relevant commit information

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-block-committer#59]
Define a mechanism for allowing fuel-core to query gas cost and other relevant information to adjust block building time, size, and general gas cost.

**Comment by segfault-magnet** [comment]
Related: 
https://github.com/FuelLabs/fuel-block-committer/issues/110

Should they be merged @digorithm @MujkicA ?

**Comment by digorithm** [comment]
Yeah, this is the same as #110. Closing this in favour of the new one (since we're already tracking it).
