### ISSUE TITLE
Update contracts reference in tests

### ISSUE THREAD

**Issue by DefiCake** [FuelLabs/fuel-block-committer#84]
Some deploy scripts are going to be removed as part of a clean up on the bridge repository, they might brick current tests here.

As soon as https://github.com/FuelLabs/fuel-bridge/pull/204 is merged, I 'll open a PR to update existing Dockerfiles in this repository to point to the last version of the contracts and deploy scripts.

**Comment by segfault-magnet** [comment]
The deployment scripts are no longer used.
